using System.Collections.Generic;
using System.IO;
using UnityEditor;
using UnityEngine;

namespace LitMotion.TweenEditor.Editor
{
    /// <summary>
    /// Authors the shipped library of tween presets as <see cref="TweenAnimationAsset"/> files.
    /// </summary>
    /// <remarks>
    /// Generated by code rather than shipped as .asset files so they survive a change to the
    /// step model: regenerate and they are correct again, with no hand-merging of serialized
    /// YAML. It also keeps each preset readable as the few lines of intent it actually is.
    ///
    /// Every preset is written to be object-agnostic. Positional moves use
    /// <see cref="TweenStep.FromOffset"/> so they finish wherever the object already sits, and
    /// nothing references a scene object, so one asset can drive any number of them.
    /// </remarks>
    internal static class TweenPresetGenerator
    {
        const string DefaultFolder = "Assets/LitMotion Tween Editor/Presets";

        /// <summary>Distance a slide-in travels, in local units or UI pixels.</summary>
        const float SlideDistance = 160f;

        [MenuItem("Tools/LitMotion/Generate Tween Presets")]
        public static void GenerateAll()
        {
            var folder = EnsureFolder(DefaultFolder);
            var presets = Build();
            var written = 0;

            foreach (var pair in presets)
            {
                var path = folder + "/" + pair.Key + ".asset";
                var existing = AssetDatabase.LoadAssetAtPath<TweenAnimationAsset>(path);

                if (existing != null)
                {
                    // Overwrite in place so existing references to the asset keep working.
                    existing.SetAnimation(pair.Value);
                    EditorUtility.SetDirty(existing);
                }
                else
                {
                    var asset = ScriptableObject.CreateInstance<TweenAnimationAsset>();
                    asset.SetAnimation(pair.Value);
                    AssetDatabase.CreateAsset(asset, path);
                }

                written++;
            }

            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();

            Debug.Log($"[LitMotion Tween Editor] Wrote {written} tween presets to {folder}.");

            var first = AssetDatabase.LoadAssetAtPath<TweenAnimationAsset>(folder + "/FadeIn.asset");
            if (first != null) EditorGUIUtility.PingObject(first);
        }

        /// <summary>The preset library, keyed by asset file name.</summary>
        /// <remarks>Internal so the tests can build and verify every preset without touching disk.</remarks>
        internal static Dictionary<string, TweenAnimation> Build()
        {
            var presets = new Dictionary<string, TweenAnimation>
            {
                ["FadeIn"] = Animation(TweenAnimationId.Show, FadeTo(1f, 0.25f, Ease.OutQuad, from: 0f)),
                ["FadeOut"] = Animation(TweenAnimationId.Hide, FadeTo(0f, 0.2f, Ease.InQuad)),

                ["PopIn"] = Animation(TweenAnimationId.Show,
                    UniformScale(0.6f, 1f, 0.3f, Ease.OutBack),
                    FadeTo(1f, 0.18f, Ease.OutQuad, from: 0f)),

                ["BounceIn"] = Animation(TweenAnimationId.Show,
                    UniformScale(0.3f, 1f, 0.55f, Ease.OutBounce),
                    FadeTo(1f, 0.2f, Ease.OutQuad, from: 0f)),

                ["ElasticPop"] = Animation(TweenAnimationId.Show,
                    UniformScale(0.5f, 1f, 0.6f, Ease.OutElastic)),

                ["PanelPopIn"] = Animation(TweenAnimationId.Show,
                    SlideFrom(new Vector3(0f, -40f, 0f), 0.3f, Ease.OutCubic),
                    UniformScale(0.92f, 1f, 0.3f, Ease.OutBack),
                    FadeTo(1f, 0.2f, Ease.OutQuad, from: 0f)),

                ["SlideInLeft"] = SlideIn(new Vector3(-SlideDistance, 0f, 0f)),
                ["SlideInRight"] = SlideIn(new Vector3(SlideDistance, 0f, 0f)),
                ["SlideInTop"] = SlideIn(new Vector3(0f, SlideDistance, 0f)),
                ["SlideInBottom"] = SlideIn(new Vector3(0f, -SlideDistance, 0f)),

                ["PunchFeedback"] = Animation(TweenAnimationId.Click,
                    Vibration(TweenType.Punch, TweenChannel.Scale, new Vector3(0.2f, 0.2f, 0.2f), 0.35f, 8)),

                ["ShakeError"] = Animation(TweenAnimationId.Click,
                    Vibration(TweenType.Shake, TweenChannel.Position, new Vector3(12f, 0f, 0f), 0.4f, 20)),

                ["Jump"] = Animation("Jump", Hop()),
            };

            // Pulse breathes forever, which only the animation-level loop can express: a step
            // that loops indefinitely cannot be scheduled inside a sequence.
            var pulse = Animation("Pulse", UniformScaleFromCurrent(1.08f, 0.6f, Ease.InOutSine));
            pulse.Loops = -1;
            pulse.LoopType = LoopType.Yoyo;
            presets["Pulse"] = pulse;

            return presets;
        }

        // --- Builders ---

        static TweenAnimation Animation(string id, params TweenStep[] steps)
        {
            var animation = new TweenAnimation { Id = id };
            animation.Steps.Clear();
            animation.Steps.AddRange(steps);
            return animation;
        }

        static TweenAnimation SlideIn(Vector3 offset)
        {
            return Animation(TweenAnimationId.Show,
                SlideFrom(offset, 0.35f, Ease.OutCubic),
                FadeTo(1f, 0.25f, Ease.OutQuad, from: 0f));
        }

        static TweenStep Step(TweenType type, float duration, Ease ease)
        {
            var step = new TweenStep
            {
                Type = type,
                Duration = duration,
                Ease = ease,
                Enabled = true,
                Loops = 1,
                FromCurrent = true,
            };

            return step;
        }

        static TweenStep SlideFrom(Vector3 offset, float duration, Ease ease)
        {
            var step = Step(TweenType.Move, duration, ease);
            step.Label = "Slide";
            step.FromOffset = true;
            step.From = offset;
            return step;
        }

        static TweenStep FadeTo(float alpha, float duration, Ease ease, float? from = null)
        {
            var step = Step(TweenType.Fade, duration, ease);
            step.Label = "Fade";
            step.To = new Vector4(alpha, 0f, 0f, 0f);

            if (from.HasValue)
            {
                step.FromCurrent = false;
                step.From = new Vector4(from.Value, 0f, 0f, 0f);
            }

            return step;
        }

        static TweenStep UniformScale(float from, float to, float duration, Ease ease)
        {
            var step = Step(TweenType.Scale, duration, ease);
            step.Label = "Scale";
            step.UniformScale = true;
            step.FromCurrent = false;
            step.From = new Vector4(from, from, from, 0f);
            step.To = new Vector4(to, to, to, 0f);
            return step;
        }

        static TweenStep UniformScaleFromCurrent(float to, float duration, Ease ease)
        {
            var step = Step(TweenType.Scale, duration, ease);
            step.Label = "Scale";
            step.UniformScale = true;
            step.FromCurrent = true;
            step.To = new Vector4(to, to, to, 0f);
            return step;
        }

        static TweenStep Vibration(TweenType type, TweenChannel channel, Vector3 strength,
            float duration, int frequency)
        {
            // Punch and Shake read the end value as an oscillation strength, and both ride on
            // their own envelope, so linear easing is what gives the authored shape.
            var step = Step(type, duration, Ease.Linear);
            step.Label = type.ToString();
            step.Channel = channel;
            step.To = strength;
            step.Frequency = frequency;
            step.DampingRatio = 1f;
            step.RandomSeed = type == TweenType.Shake ? 1u : 0u;
            return step;
        }

        static TweenStep Hop()
        {
            var step = Step(TweenType.Jump, 0.5f, Ease.Linear);
            step.Label = "Hop";

            // Relative to zero: leaves and lands on the same spot, so the arc is the whole
            // motion and the preset works wherever it is applied.
            step.Relative = true;
            step.To = Vector4.zero;
            step.JumpCount = 1;
            step.JumpPower = 60f;
            return step;
        }

        static string EnsureFolder(string folder)
        {
            if (AssetDatabase.IsValidFolder(folder)) return folder;

            var parent = Path.GetDirectoryName(folder)?.Replace('\\', '/');
            var leaf = Path.GetFileName(folder);

            if (string.IsNullOrEmpty(parent) || !AssetDatabase.IsValidFolder(parent))
            {
                // The package folder was moved or renamed, so fall back to somewhere that exists
                // rather than failing the whole generation.
                return "Assets";
            }

            AssetDatabase.CreateFolder(parent, leaf);
            return folder;
        }
    }
}
